#pragma config(Sensor, in1,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    middleLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in4,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl2,  sonarIn,        sensorSONAR_raw)
#pragma config(Sensor, dgtl5,  pushButton,     sensorTouch)
#pragma config(Sensor, dgtl6,  redLED,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  yellowLED,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  greenLED,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  encoderRight,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, encoderLeft,    sensorQuadEncoder)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Activity 3.1.1 Inputs and Outputs
  Team Members: Byron Sharman
  Date: 3/31/2021
  Section:


  Task Description:
  After a button push, drive forward for exactly 2 feet. Turn on the green LED while driving;
  turn on the red LED for one second after stopping.


  Pseudocode:
  wait for button push
  start motors
  count encoders until 2 feet have gone by
  stop motors


*/

//circumference in inches
//pi*d
static const float circumference = 3.1415927*2.75;

task main()
{                                     //Program begins, insert code within curly braces
	while (true)
	{
		untilTouch(pushButton);
		startMotor(leftMotor, 120);
		startMotor(rightMotor, 119);
		//360 encoder counts per revolution
		//1 revolution per circumference length gone forward
		//24 inches in 2 feet
		untilEncoderCounts(360*24/circumference, encoderLeft);
		stopMotor(leftMotor);
		stopMotor(rightMotor);
	}
}
