#pragma config(Sensor, in1,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    middleLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in4,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl2,  sonarIn,        sensorSONAR_raw)
#pragma config(Sensor, dgtl5,  pushButton,     sensorTouch)
#pragma config(Sensor, dgtl6,  redLED,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  yellowLED,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  greenLED,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  encoderRight,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, encoderLeft,    sensorQuadEncoder)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Activity 3.1.1 Inputs and Outputs
  Team Members: Byron Sharman
  Date: 3/31/2021
  Section:


  Task Description:
  Set your TWR in the green box and wait for the button to be pushed.
  Then turn on the flashlight and travel from the start box to the red
  box while going around the X. The robot must not tuch the black line
  or the X. When your TWR is in the red box, it should stop and turn
  off the flashlight. The entire TWR must be fully in the red box. This
  needs to be repeatable; you may be asked to run your progrma more than
  once.


  Pseudocode:
  wait for a button push
  turn on the flashlight
  turn on both motors
  wait until the line and X are passed
  reverse the right motor to turn in place pi/2 radians
  make the right motor go forward again
  wait until the robot is clear of the obstacles
  reverse the right motor to turn in place pi/2 radians
  make the right motor go forward again
  wait until the robot is in the red box
  stop both motors
  turn off the flashlight


*/

//circumference in inches
//pi*d
static const float circumference = 3.1415927*2.75;

static const int speedLeft = 122;
static const int speedRight = 121;

task flash()
{
	turnLEDOn(yellowLED);
	waitInMilliseconds(300);
	turnLEDOff(yellowLED);
}

//in-place turn right (goal is a quarter turn)
void turnRight()
{
	//stopMotor(rightMotor);
	startMotor(rightMotor, -speedRight);
	untilEncoderCounts(-360*0.0216/circumference, encoderRight);
	startMotor(rightMotor, speedRight);
}

task main()
{                                     //Program begins, insert code within curly braces
	while (true)
	{
		untilTouch(pushButton);
		turnFlashlightOn(flashlight, 127);
		//forward
		//it would be good to make constants for the power we give motors
		//that way, we only have to change two numbers if we want to change speed
		startMotor(leftMotor, speedLeft);
		startMotor(rightMotor, speedRight);
		untilEncoderCounts(360*48/circumference, encoderLeft);
		turnRight();
		//turn finished: we should be perpendicular to the line
		untilEncoderCounts(360*24/circumference, encoderLeft);
		turnRight();
		//turn finished: we should be parallel to the line
		//now travel forward until the TWR is in the red box
		untilEncoderCounts(360*48/circumference, encoderLeft);
		stopMotor(leftMotor);
		stopMotor(rightMotor);
		turnFlashlightOff(flashlight);
	}
}
