#pragma config(Sensor, in1,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    middleLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in4,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl2,  sonarIn,        sensorSONAR_raw)
#pragma config(Sensor, dgtl5,  pushButton,     sensorTouch)
#pragma config(Sensor, dgtl6,  redLED,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  yellowLED,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  greenLED,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  encoderRight,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, encoderLeft,    sensorQuadEncoder)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Activity 3.1.1 Inputs and Outputs
  Team Members: Byron Sharman
  Date: 3/31/2021
  Section:


  Task Description:
  Drive in a straight line, turn around, and come back. Turn on the
  green LED while driving and turn on the red LED after stopping.


  Pseudocode:
  wait for button push (assumes human has put it in the green box)
  turn on green LED
  turn on left and right motors
  wait 3 seconds
  turn off right motor
  wait a magic number of milliseconds
  turn on right motor
  wait 3 seconds
  turn off motors
  turn on red LED
  wait 1 second
  turn off red LED
  go back to beginning (while loop)




*/

task end()
{
    stopMotor(rightMotor);
    stopMotor(leftMotor);
    turnLEDOff(greenLED);
    turnLEDOn(redLED);
    wait(1);
    turnLEDOff(redLED);
}

task main()
{                                     //Program begins, insert code within curly braces

    //things to do:
    //write consts in the template file for the left and right motor speeds
    //    (do consts exist in robotC?)
    //    I have seen that sometimes the motors don't spin the same speed
    while (true) {
    	  untilTouch(pushButton);
    	  turnLEDOn(greenLED);
    	  //to go straight, both motors must be started
    	  startMotor(leftMotor, 50);
    	  startMotor(rightMotor, 50);
    	  wait(3);
    	  //reversing one of the motors should result in an in-place turn
    	  startMotor(rightMotor, -50);
    	  waitInMilliseconds(1582); //with timers, we have to shoot in the dark until it roughly works
    	  startMotor(rightMotor, 50);
    	  wait(3);
    	  startTask(end);
    }

}
