#pragma config(Sensor, in1,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in4,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl2,  sonarIn,        sensorSONAR_inch)
#pragma config(Sensor, dgtl5,  pushButton,     sensorTouch)
#pragma config(Sensor, dgtl6,  redLED,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  yellowLED,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  greenLED,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  encoderRight,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, encoderLeft,    sensorQuadEncoder)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Activity 3.1.1 Inputs and Outputs
  Team Members: Byron Sharman
  Date: 3/31/2021
  Section:


  Task Description:
  Wait for a button  push, then drive until ten inches from the wall. Turn on the green LED
  while driving and turn on the red LED for one second after stopping.


  Pseudocode:
  wait for button push
  turn on green LED
  turn on both motors
  wait until sonarIn reads 10
  turn off both motors
  turn off the green LED
  turn on the red LED
  wait 1 second
  turn off the red LED



*/

task main()
{                                     //Program begins, insert code within curly braces

		while (true) {
			untilTouch(pushButton);
			turnLEDOn(greenLED);
			startMotor(leftMotor, 50);
			startMotor(rightMotor, 50);
			untilSonarLessThan(10, sonarIn);
			stopMotor(leftMotor);
			stopMotor(rightMotor);
			turnLEDOff(greenLED);
			turnLEDOn(redLED);
			wait(1);
			turnLEDOff(redLED);
	}
}
