#pragma config(Sensor, in1,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    middleLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in4,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl2,  sonarIn,        sensorSONAR_raw)
#pragma config(Sensor, dgtl5,  pushButton,     sensorTouch)
#pragma config(Sensor, dgtl6,  redLED,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  yellowLED,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  greenLED,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  encoderRight,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, encoderLeft,    sensorQuadEncoder)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Activity 3.1.1 Inputs and Outputs
  Team Members: Byron Sharman
  Date: 3/31/2021
  Section:


  Task Description:
  Start in the green box, drive forward for 3 seconds, turn around, and drive
  back - thrice. (Use a loop to use the same code). Turn on the green LED while
  driving and turn on the red LED for 1 second after stopping.


  Pseudocode:
  wait for button push
  turn on green LED
  turn both motors on
  wait 3 seconds
  turn motors on, but in opposite directions
  wait until the robot is facing the opposite way
  make the "backward" motor go forward at the same speed as the other motor
  wait 3 seconds
  repeat 180° turn
  repeat the whole process twice more, but switch which motor is reversed during the turn every time


*/

static const int speedLeft = 50;
static const int speedRight = 49;
static const int turnTime = 1800;

task main() {
    while (true) {
        untilTouch(pushButton);
        turnLEDOn(greenLED);
        waitInMilliseconds(888);
        startMotor(leftMotor, speedLeft);
        startMotor(rightMotor, speedRight);
        //do the stuff in brackets 3 times
        for (int i=0; i<=5; i++) {
            wait(3);
            //reversing one of the motors should result in an in-place turn
            startMotor(rightMotor, -speedRight);
            waitInMilliseconds(turnTime);
            //now we go straight again
            startMotor(rightMotor, speedRight + (i%2));
        }
        stopMotor(leftMotor);
        stopMotor(rightMotor);
        turnLEDOff(greenLED);
        turnLEDOn(redLED);
        wait(1);
        turnLEDOff(redLED);
    }
}
