#pragma config(Sensor, in1,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    middleLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in4,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl2,  sonarIn,        sensorSONAR_raw)
#pragma config(Sensor, dgtl5,  pushButton,     sensorTouch)
#pragma config(Sensor, dgtl6,  redLED,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  yellowLED,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  greenLED,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  encoderRight,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, encoderLeft,    sensorQuadEncoder)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Activity 3.1.1 Inputs and Outputs
  Team Members: Byron Sharman
  Date: 3/31/2021
  Section:


  Task Description:
  Use variables to program your TWR to turn on the yellow LED for one second and then
  off for one second, repeat 10 times and then turn on the green LED for 0.5 seconds
  and then off for 0.75 seconds, repeat 10 times.


  Pseudocode:
  looks like instead of a for loop, we are supposed to do a while loop with a counter
  first loop:
    turn yellow LED on
    wait 1 second
    turn yellow LED off
    wait 1 second
  second loop:
    turn green LED on
    wait 0.l5 seconds
    turn green LED off
    wait 0.75 seconds


*/

task main()
{                                     //Program begins, insert code within curly braces

    int counter = 0;
    while (counter < 10) {
        turnLEDOn(yellowLED);
        wait(1);
        turnLEDOff(yellowLED);
        wait(1);
        counter++;
    }
    counter = 0;
    while (counter < 10) {
        turnLEDOn(greenLED);
        wait(0.5);
        turnLEDOff(greenLED);
        wait(0.75);
        counter++;
    }

}
