#pragma config(Sensor, in1,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    middleLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in4,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl2,  sonarIn,        sensorSONAR_raw)
#pragma config(Sensor, dgtl5,  pushButton,     sensorTouch)
#pragma config(Sensor, dgtl6,  redLED,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  yellowLED,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  greenLED,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  encoderRight,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, encoderLeft,    sensorQuadEncoder)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Activity 3.1.1 Inputs and Outputs
  Team Members: Byron Sharman
  Date: 3/31/2021
  Section:


  Task Description:
  Set your TWR in the green box and wait for the button to be pushed.
  Then turn on the flashlight and travel from the start box to the red
  box while going around the X. The robot must not tuch the black line
  or the X. When your TWR is in the red box, it should stop and turn
  off the flashlight. The entire TWR must be fully in the red box. This
  needs to be repeatable; you may be asked to run your progrma more than
  once.


  Pseudocode:
  wait for a button push
  turn on the flashlight
  turn on both motors
  wait until the line and X are passed (requires guessing)
  reverse the right motor to turn in place pi/2 radians
  make the right motor go forward again
  wait until the robot is clear of the obstacles (requires guessing)
  reverse the right motor to turn in place pi/2 radians
  make the right motor go forward again
  wait until the robot is in the red box (requires guessing)
  stop both motors
  turn off the flashlight


*/

//in-place turn right (goal is a quarter turn)
task turnRight()
{
        startMotor(rightMotor, -60);
        waitInMilliseconds(725);
        startMotor(rightMotor, 60);
}

task main()
{                                     //Program begins, insert code within curly braces

    while (true) {
        untilTouch(pushButton);
        turnFlashlightOn(flashlight);
        //forward
        //it would be good to make constants for the power we give motors
        //that way, we only have to change two numbers if we want to change speed
        startMotor(leftMotor, 60);
        startMotor(rightMotor, 60);
        //magic guessing number
        waitInMilliseconds(5588);
        //words of wisdom from your former self: MAKE SURE TASKS AREN'T ASYNCHRONOUS
        //could I just use functions?
        startTask(turnRight);
        //turn finished: we should be perpendicular to the line
        waitInMilliseconds(3333);
        startTask(turnRight);
        //turn finished: we should be parallel to the line
        //now travel forward until the TWR is in the red box
        waitInMilliseconds(4488);
        stopMotor(leftMotor);
        stopMotor(rightMotor);
        turnFlashlightOff(flashlight);


    }


}
