#pragma config(Sensor, in1,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    middleLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in4,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl2,  sonarIn,        sensorSONAR_raw)
#pragma config(Sensor, dgtl5,  pushButton,     sensorTouch)
#pragma config(Sensor, dgtl6,  redLED,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  yellowLED,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  greenLED,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  encoderRight,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, encoderLeft,    sensorQuadEncoder)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Activity 3.1.1 Inputs and Outputs
  Team Members: Byron Sharman
  Date: 3/31/2021
  Section:


  Task Description:
  Place your TWR in the green start box and have it wait for the button to be
  pushed then turn on the green LED, drive forward in a straight line, following
  the blue tape line, for 3 seconds, stop, turn around 180°, drive back to the
  green start box, stop, turn around 180°. Do this 3 times using variables. At
  the end your TWR should stop back completely in the green start box and then
  turn on the red LED for 1 second. This needs to be repeatable so you may be
  asked to run your program more than once.


  Pseudocode:
  wait for button push
  turn on green LED
  turn both motors on
  wait 3 seconds
  turn both motors off
  turn motors on, but in opposite directions
  wait 1.582 seconds
  make the "backward" motor go forward at the same speed as the other motor
  wait 3 seconds
  repeat 180° turn
  repeat the whole process twice more


*/

//makes a turn at speed 50 and ends with both motors on in the same direction.
task turnAround()
{
    startMotor(leftMotor, 50);
    //reversing one of the motors should result in an in-place turn
    startMotor(rightMotor, -50);
    waitInMilliseconds(1582);
    startMotor(rightMotor, 50);
}

task main()
{                                     //Program begins, insert code within curly braces
    while (true) {
        untilTouch(pushButton);
        turnLEDOn(greenLED);
        for (int i=0; i<=2; i++) {
            startMotor(leftMotor, 50);
            startMotor(rightMotor, 50);
            wait(3);
            //presumably, the following two lines will have no effect
            stopMotor(leftMotor);
            stopMotor(rightMotor);
            startTask(turnAround);
            wait(3);
            startTask(turnAround);
        }
        turnLEDOff(greenLED);
        turnLEDOn(redLED);
        wait(1);
        turnLEDOff(redLED);
    }

}
